writing_task:
  description: >
    Create detailed and comprehensive reporting content for {topic} based on the provided research, your existing knowledge, and content plan. The content should be
    tailored for a {audience_level} audience, explaining concepts thoroughly and at an appropriate level of complexity. Follow
    the content plan structure while ensuring the writing is engaging, technically accurate, and in-depth. Thoroughness, completeness, and depth are key.

    Section details: {section}

    IMPORTANT: The section details may be provided in different formats. First, try to parse it as JSON to extract the title, high_level_goal, why_important, sources, and content_outline fields.
    If the JSON parsing fails, use the information as provided.
    
    Focus on addressing all the points specified in the content outline and make sure to reference the provided sources.
    
    Your output MUST be the complete section content formatted with proper headings and structure.
  expected_output: >
    A well-structured and comprehensive section that will be part of a longer form content piece that follows the 
    content plan and effectively presents {topic} to {audience_level} level readers. Completeness, thoroughness, and depth are key. Use analogies,
    examples, and detailed explanations to help explain the content when appropriate.

    Ensure the content is formatted with clear headings and subheadings, and use bullet points where appropriate to enhance readability.

    No need to include summaries or conclusions of each section, just the content.
  agent: content_writer
  async: false

editing_task:
  description: >
    Review and refine the written reporting content for {topic}. Ensure it maintains high quality standards, follows the
    content plan precisely, and effectively communicates all objectives. Pay special attention to language level,
    examples, and explanations to verify they are appropriate for {audience_level} readers while preserving technical accuracy.
    Thoroughness, completeness, and depth are key.

    Section: {section}
  expected_output: >
    A polished and comprehensive version of the reporting content with improved clarity, appropriate complexity level, and enhanced readability
    for {audience_level} readers. Ensure the content is formatted with clear headings and subheadings, and use bullet points where appropriate to enhance readability.

    We only want the section content back, nothing else. Do not include the feedback.
  agent: editor
  async: false

quality_review_task:
  description: >
    Perform a comprehensive quality assessment of the final reporting content for {topic}. Evaluate against reporting best
    practices and verify alignment with {audience_level} level expectations. Check that all sections from the content plan are
    covered adequately, concepts build logically, and objectives are met effectively. Thoroughness, completeness, and depth are key.

    Section: {section}

    IMPORTANT: Your final output MUST be the complete, improved content after your quality review. Do not just return 
    a review or assessment - return the actual full content that should appear in the report.
  expected_output: >
    The complete, high-quality content for this section of the report, with all improvements incorporated.
    This is the FINAL content that will appear in the report, not just feedback or analysis.
    The content should include proper formatting with clear headings, subheadings, and bullet points where appropriate.
    Include references to sources as inline citations or hyperlinks within the content.
  agent: quality_reviewer 
  async: true 