writing_task:
  description: >
    Create comprehensive educational content for {topic} based on the provided research and content plan. The content should be
    tailored for a {audience_level} audience, explaining concepts clearly and at an appropriate level of complexity. Follow
    the content plan structure while ensuring the writing is engaging and technically accurate.

    Section: {section}
  expected_output: >
    A well-structured paragraph or paragraphs of this section that will be part of a longer form content piece that follows the 
    content plan and effectively teaches {topic} to {audience_level} level learners.

    No need to always use bullet points, just use them if it makes sense.

    No need to include summaries or conclusions of each section, just the content.
  agent: content_writer

editing_task:
  description: >
    Review and refine the written educational content for {topic}. Ensure it maintains high quality standards, follows the
    content plan precisely, and effectively communicates all learning objectives. Pay special attention to language level,
    examples, and explanations to verify they are appropriate for {audience_level} learners while preserving technical accuracy.

    Section: {section}
  expected_output: >
    A polished version of the educational content with improved clarity, appropriate complexity level, and enhanced readability
    for {audience_level} learners. We only want the section content back, nothing else. Do not include the feedback.
  agent: editor

quality_review_task:
  description: >
    Perform a comprehensive quality assessment of the final educational content for {topic}. Evaluate against educational best
    practices and verify alignment with {audience_level} level expectations. Check that all sections from the content plan are
    covered adequately, concepts build logically, and learning objectives are met effectively.

    Section: {section}
  expected_output: >
    I want an improved version of the section content that incorporates the feedback. Do not include the feedback itself, just the improved content.
  agent: quality_reviewer
